### ISSUE TITLE
Cannot pull dependencies on PHP 8.4 souce branch

### ISSUE THREAD

**Issue by Bilge** [php/php-sdk-binary-tools#11]
Current version of `php-src@master` fails when running `phpsdk_deps -u` with the following:

```
Fatal error: Uncaught SDK\Exception: Unsupported branch '8.4' in D:\php-sdk\lib\php\libsdk\SDK\Config.php:183
Stack trace:
#0 D:\php-sdk\bin\phpsdk_deps.php(105): SDK\Config::setCurrentBranchName('8.4')
#1 {main}
  thrown in D:\php-sdk\lib\php\libsdk\SDK\Config.php on line 183
```

It appears to be because the definition for 8.4 is absent from http://downloads.php.net/~windows/php-sdk/deps/series/.

**Comment by cmb69** [comment]
This has been resolved about a week ago. Note though that so far we only made the series files for a new PHP minor/major release available shortly before the respective first alpha releases, i.e. basically what we did for PHP 8.4. I don't see any need to change that, because even now, there is no `PHP-8.4` branch, and `master` should be detected and work fine.
