### ISSUE TITLE
[Windows ARM64] Uncaught SDK\Exception: phpsdk_deps

### ISSUE THREAD

**Issue by jamespack** [php/php-sdk-binary-tools#39]
`phpsdk_deps --update --branch master` fails to update deps due to a missing nuget config for arm64.
```
Fatal error: Uncaught SDK\Exception: Failed to find config with arch 'arm64' in D:\php-sdk-binary-tools\lib\php\libsdk\SDK\Config.php:307
Stack trace:
#0 D:\php-sdk-binary-tools\bin\phpsdk_deps.php(134): SDK\Config::getCurrentBranchData()
#1 {main}
  thrown in D:\php-sdk-binary-tools\lib\php\libsdk\SDK\Config.php on line 307
```

Anything the community can do to help here?

**Comment by cmb69** [comment]
There is no nuget involved. The dependencies are build via https://github.com/winlibs/winlib-builder, and then provided on https://downloads.php.net/~windows/php-sdk/deps/. Since we have not built dependencies for ARM64, `phpsdk_deps` is supposed to fail. See https://github.com/php/php-src/issues/15610 for some further background.

**Comment by jamespack** [comment]
Thx
